#version: '3.9'
services:
  mysqlService:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Toyota88@
      MYSQL_DATABASE: mylobby
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always

  tcpServer:
    image: charat/dest-tcp:latest
    ports:
      - 5400:5400
    environment:
      DEBUG_MODE: false
      VERSION: 0.1.6b
      IP_OUTPUT: 10.19.4.8
    depends_on:
      - mysqlService
    restart: always

  backServer:
    image: charat/dest-back:latest
    ports:
      - 3000:3000
      - 52000:52000/udp
    environment:
      DEBUG_MODE: false
      IP_MITSU: 10.19.4.11
      IP_Backend: backServer
      LINE_NOTIFY_TOKEN: ZcuasZl67YahoAeTyAvQ7loyL9RU2twtbqqizkfIhp6 
      DATABASE_IP: mysqlService
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Toyota88@
      DATABASE_DB_NAME: mylobby
    depends_on:
      - tcpServer
    restart: always

  frontServer:
    image: charat/dest-front:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backServer
    restart: always
