version: '3.9'
services:
  tcpServer:
    image: charat/dest-back:latest
    ports:
      - 3000:3000
      - 52000:52000/udp
    environment:
      DEBUG_MODE: false
      IP_MITSU: 10.19.4.11
      DATABASE_IP: 10.19.4.8
      LINE_NOTIFY_TOKEN: ZcuasZl67YahoAeTyAvQ7loyL9RU2twtbqqizkfIhp6
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Toyota88@
      DATABASE_DB_NAME: mylobby
    restart: always
