version: '3'
services:
  mysqlService:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: Toyota88@
      MYSQL_DATABASE: mylobby
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always


  destBack:
    image: charat/dest-lift:latest
    ports:
      - 3000:3000
    environment:
      #IP_MITSU: 10.19.4.11   #กำหนด IP ของ Lift-mitsu  (host.docker.internal แทน127.0.0.1)
      IP_MITSU: 10.19.4.11
      VERSION: Dest-Back:0.1.4a
      LINE_SECRET: ZcuasZl67YahoAeTyAvQ7loyL9RU2twtbqqizkfIhp6
      DATABASE_IP: mysqlService
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Toyota88@
      DATABASE_DB_NAME: mylobby  
    restart: always
    depends_on:
      - mysqlService

  tcpServer:
    image: charat/dest-tcp:latest
    ports:
      - "5400:5400"
    environment:
      DEBUG_MODE: false
      VERSION: 0.1.6b
      IP_OUTPUT: destBack
    restart: always





